SlashCommandList = {
	["NormalizedCommands"] = {
		["/pvp"] = {
			["/pvp"] = true,
		},
		["/calendar"] = {
			["/calendar"] = true,
		},
		["/logout"] = {
			["/logout"] = true,
			["/camp"] = true,
		},
		["/y"] = {
			["/shout"] = true,
			["/y"] = true,
			["/yell"] = true,
			["/sh"] = true,
		},
		["/petattack"] = {
			["/petattack"] = true,
		},
		["/targetparty"] = {
			["/targetparty"] = true,
		},
		["/ckick"] = {
			["/ckick"] = true,
		},
		["/stopcasting"] = {
			["/stopcasting"] = true,
		},
		["/resetcommentatorsettings"] = {
			["/resetcommentatorsettings"] = true,
		},
		["/petmoveto"] = {
			["/petmoveto"] = true,
		},
		["/a"] = {
			["/a"] = true,
			["/assist"] = true,
		},
		["/petautocaston"] = {
			["/petautocaston"] = true,
		},
		["/mute"] = {
			["/unvoice"] = true,
			["/squelch"] = true,
			["/mute"] = true,
		},
		["/targetlasttarget"] = {
			["/targetlasttarget"] = true,
		},
		["/gdisband"] = {
			["/guilddisband"] = true,
			["/gdisband"] = true,
		},
		["/cast"] = {
			["/cast"] = true,
			["/spell"] = true,
		},
		["/mod"] = {
			["/moderator"] = true,
			["/mod"] = true,
		},
		["/mtoff"] = {
			["/mtoff"] = true,
			["/maintankoff"] = true,
		},
		["/cv"] = {
			["/cv"] = true,
		},
		["/time"] = {
			["/time"] = true,
		},
		["/p"] = {
			["/party"] = true,
			["/p"] = true,
		},
		["/removefriend"] = {
			["/removefriend"] = true,
			["/remfriend"] = true,
		},
		["/stopattack"] = {
			["/stopattack"] = true,
		},
		["/framestack"] = {
			["/fstack"] = true,
			["/framestack"] = true,
		},
		["/announce"] = {
			["/announce"] = true,
			["/ann"] = true,
		},
		["/ghelp"] = {
			["/ghelp"] = true,
			["/guildhelp"] = true,
		},
		["/friends"] = {
			["/friends"] = true,
			["/friend"] = true,
		},
		["/macrohelp"] = {
			["/macrohelp"] = true,
		},
		["/petfollow"] = {
			["/petfollow"] = true,
		},
		["/targetenemyplayer"] = {
			["/targetenemyplayer"] = true,
		},
		["/ginvite"] = {
			["/ginvite"] = true,
			["/guildinvite"] = true,
		},
		["/teamdisband"] = {
			["/teamdisband"] = true,
			["/tdisband"] = true,
		},
		["/enableaddons"] = {
			["/enableaddons"] = true,
		},
		["/join"] = {
			["/join"] = true,
			["/channel"] = true,
			["/chan"] = true,
		},
		["/stopwatch"] = {
			["/stopwatch"] = true,
			["/timer"] = true,
			["/sw"] = true,
		},
		["/target"] = {
			["/target"] = true,
			["/tar"] = true,
		},
		["/w"] = {
			["/w"] = true,
			["/t"] = true,
			["/whisper"] = true,
			["/tell"] = true,
			["/send"] = true,
		},
		["/ins"] = {
			["/inspect"] = true,
			["/ins"] = true,
		},
		["/tm"] = {
			["/tm"] = true,
			["/targetmarker"] = true,
		},
		["/raidfinder"] = {
			["/raidfinder"] = true,
			["/rf"] = true,
			["/lfr"] = true,
		},
		["/gdemote"] = {
			["/guilddemote"] = true,
			["/gdemote"] = true,
		},
		["/o"] = {
			["/osay"] = true,
			["/o"] = true,
			["/officer"] = true,
		},
		["/targetenemy"] = {
			["/targetenemy"] = true,
		},
		["/owner"] = {
			["/owner"] = true,
		},
		["/g"] = {
			["/gc"] = true,
			["/g"] = true,
			["/guild"] = true,
			["/gu"] = true,
		},
		["/gmotd"] = {
			["/gmotd"] = true,
			["/guildmotd"] = true,
		},
		["/unban"] = {
			["/unban"] = true,
		},
		["/cancelqueuedspell"] = {
			["/cancelqueuedspell"] = true,
			["/cqs"] = true,
		},
		["/assignplayer"] = {
			["/ap"] = true,
			["/assignplayer"] = true,
		},
		["/clearfocus"] = {
			["/clearfocus"] = true,
		},
		["/played"] = {
			["/played"] = true,
		},
		["/token"] = {
			["/tk"] = true,
			["/token"] = true,
		},
		["/swapactionbar"] = {
			["/swapactionbar"] = true,
		},
		["/inv"] = {
			["/inv"] = true,
			["/invite"] = true,
		},
		["/dump"] = {
			["/dump"] = true,
		},
		["/castsequence"] = {
			["/castsequence"] = true,
		},
		["/equipset"] = {
			["/equipset"] = true,
		},
		["/petdismiss"] = {
			["/petdismiss"] = true,
		},
		["/rw"] = {
			["/rw"] = true,
		},
		["/greplace"] = {
			["/greplace"] = true,
		},
		["/cancelaura"] = {
			["/cancelaura"] = true,
		},
		["/f"] = {
			["/fol"] = true,
			["/f"] = true,
			["/follow"] = true,
		},
		["/invitespectatormatch"] = {
			["/invitespectatormatch"] = true,
		},
		["/disableaddons"] = {
			["/disableaddons"] = true,
		},
		["/wargame"] = {
			["/wg"] = true,
			["/wargame"] = true,
		},
		["/gremove"] = {
			["/gremove"] = true,
			["/guildremove"] = true,
		},
		["/click"] = {
			["/click"] = true,
		},
		["/startattack"] = {
			["/startattack"] = true,
		},
		["/use"] = {
			["/use"] = true,
		},
		["/needbeforegreed"] = {
			["/needbeforegreed"] = true,
		},
		["/petdefensive"] = {
			["/petdefensive"] = true,
		},
		["/u"] = {
			["/votekick"] = true,
			["/u"] = true,
			["/uninvite"] = true,
			["/kick"] = true,
			["/un"] = true,
		},
		["/dungeonfinder"] = {
			["/dungeonfinder"] = true,
			["/lfd"] = true,
			["/df"] = true,
		},
		["/loot"] = {
			["/lootrolls"] = true,
			["/loot"] = true,
		},
		["/castrandom"] = {
			["/castrandom"] = true,
		},
		["/raid"] = {
			["/rsay"] = true,
			["/raid"] = true,
			["/ra"] = true,
		},
		["/teaminvite"] = {
			["/teaminvite"] = true,
			["/tinvite"] = true,
		},
		["/dismisspet"] = {
			["/dismisspet"] = true,
		},
		["/timetest"] = {
			["/timetest"] = true,
		},
		["/focus"] = {
			["/focus"] = true,
		},
		["/group"] = {
			["/group"] = true,
		},
		["/chatlist"] = {
			["/chatlist"] = true,
			["/chatwho"] = true,
			["/chatinfo"] = true,
		},
		["/randomfavoritepet"] = {
			["/rfp"] = true,
			["/randomfavoritepet"] = true,
		},
		["/requestinvite"] = {
			["/requestinvite"] = true,
		},
		["/petaggressive"] = {
			["/petaggressive"] = true,
		},
		["/castglyph"] = {
			["/castglyph"] = true,
		},
		["/userandom"] = {
			["/userandom"] = true,
		},
		["/buggrabber"] = {
			["/buggrabber"] = true,
		},
		["/raidinfo"] = {
			["/raidinfo"] = true,
		},
		["/resetchat"] = {
			["/resetchat"] = true,
		},
		["/pr"] = {
			["/promote"] = true,
			["/pr"] = true,
		},
		["/who"] = {
			["/who"] = true,
		},
		["/gv"] = {
			["/gv"] = true,
		},
		["/targetfriendplayer"] = {
			["/targetfriendplayer"] = true,
		},
		["/countdown"] = {
			["/countdown"] = true,
		},
		["/quit"] = {
			["/quit"] = true,
			["/exit"] = true,
		},
		["/dismount"] = {
			["/dismount"] = true,
		},
		["/petautocastoff"] = {
			["/petautocastoff"] = true,
		},
		["/leavevehicle"] = {
			["/leavevehicle"] = true,
		},
		["/share"] = {
			["/share"] = true,
		},
		["/script"] = {
			["/script"] = true,
			["/run"] = true,
		},
		["/ffa"] = {
			["/ffa"] = true,
		},
		["/ban"] = {
			["/ban"] = true,
		},
		["/reload"] = {
			["/reload"] = true,
		},
		["/tinspect"] = {
			["/tinspect"] = true,
			["/tableinspect"] = true,
		},
		["/equip"] = {
			["/eq"] = true,
			["/equip"] = true,
		},
		["/teamremove"] = {
			["/teamremove"] = true,
			["/tremove"] = true,
		},
		["/combatlog"] = {
			["/combatlog"] = true,
		},
		["/teamcaptain"] = {
			["/teamcaptain"] = true,
			["/tcaptain"] = true,
		},
		["/unmod"] = {
			["/unmoderator"] = true,
			["/unmod"] = true,
		},
		["/targetraid"] = {
			["/targetraid"] = true,
		},
		["/stopspelltarget"] = {
			["/stopspelltarget"] = true,
		},
		["/ignore"] = {
			["/ignore"] = true,
		},
		["/community"] = {
			["/community"] = true,
		},
		["/e"] = {
			["/emote"] = true,
			["/me"] = true,
			["/em"] = true,
			["/e"] = true,
		},
		["/clear"] = {
			["/clear"] = true,
		},
		["/h"] = {
			["/help"] = true,
			["/h"] = true,
			["/?"] = true,
		},
		["/petstay"] = {
			["/petstay"] = true,
		},
		["/moderate"] = {
			["/moderate"] = true,
		},
		["/unignore"] = {
			["/unignore"] = true,
		},
		["/gleader"] = {
			["/gleader"] = true,
			["/guildleader"] = true,
		},
		["/cinvite"] = {
			["/cinvite"] = true,
			["/chatinvite"] = true,
		},
		["/ach"] = {
			["/achieve"] = true,
			["/achievements"] = true,
			["/ach"] = true,
			["/achievement"] = true,
		},
		["/api"] = {
			["/api"] = true,
		},
		["/randompet"] = {
			["/randompet"] = true,
		},
		["/cw"] = {
			["/cw"] = true,
			["/charwhisper"] = true,
		},
		["/targetlastenemy"] = {
			["/targetlastenemy"] = true,
		},
		["/petpassive"] = {
			["/petpassive"] = true,
		},
		["/eventtrace"] = {
			["/eventtrace"] = true,
			["/etrace"] = true,
		},
		["/guildfinder"] = {
			["/guildfinder"] = true,
			["/gf"] = true,
		},
		["/leave"] = {
			["/leave"] = true,
			["/chatleave"] = true,
			["/chatexit"] = true,
		},
		["/duel"] = {
			["/duel"] = true,
		},
		["/master"] = {
			["/master"] = true,
		},
		["/teamquit"] = {
			["/teamquit"] = true,
			["/tquit"] = true,
		},
		["/s"] = {
			["/s"] = true,
			["/say"] = true,
		},
		["/changeactionbar"] = {
			["/changeactionbar"] = true,
		},
		["/tr"] = {
			["/tr"] = true,
			["/trade"] = true,
		},
		["/dnd"] = {
			["/dnd"] = true,
			["/busy"] = true,
		},
		["/saveguildroster"] = {
			["/saveguildroster"] = true,
		},
		["/password"] = {
			["/password"] = true,
			["/pass"] = true,
		},
		["/equipslot"] = {
			["/equipslot"] = true,
		},
		["/cancelform"] = {
			["/cancelform"] = true,
		},
		["/gpromote"] = {
			["/gpromote"] = true,
			["/guildpromote"] = true,
		},
		["/clearmt"] = {
			["/clearmt"] = true,
			["/clearmaintank"] = true,
		},
		["/summonpet"] = {
			["/sp"] = true,
			["/summonpet"] = true,
		},
		["/chat"] = {
			["/chat"] = true,
			["/chathelp"] = true,
		},
		["/usetalents"] = {
			["/usetalents"] = true,
		},
		["/yield"] = {
			["/yield"] = true,
			["/forfeit"] = true,
			["/concede"] = true,
		},
		["/roundrobin"] = {
			["/roundrobin"] = true,
		},
		["/console"] = {
			["/console"] = true,
		},
		["/vt"] = {
			["/vt"] = true,
		},
		["/threshold"] = {
			["/threshold"] = true,
		},
		["/i"] = {
			["/instance"] = true,
			["/battleground"] = true,
			["/i"] = true,
			["/bg"] = true,
			["/instance_chat"] = true,
		},
		["/c"] = {
			["/c"] = true,
			["/csay"] = true,
		},
		["/raidbrowser"] = {
			["/rb"] = true,
			["/or"] = true,
			["/raidbrowser"] = true,
			["/otherraids"] = true,
		},
		["/petassist"] = {
			["/petassist"] = true,
		},
		["/nameteam"] = {
			["/nt"] = true,
			["/nameteam"] = true,
		},
		["/cwm"] = {
			["/clearworldmarker"] = true,
			["/cwm"] = true,
		},
		["/clearma"] = {
			["/clearma"] = true,
			["/clearmainassist"] = true,
		},
		["/maoff"] = {
			["/maoff"] = true,
			["/mainassistoff"] = true,
		},
		["/groster"] = {
			["/groster"] = true,
			["/guildroster"] = true,
		},
		["/macro"] = {
			["/macro"] = true,
			["/m"] = true,
		},
		["/targetfriend"] = {
			["/targetfriend"] = true,
		},
		["/unmute"] = {
			["/voice"] = true,
			["/unsquelch"] = true,
			["/unmute"] = true,
		},
		["/voice"] = {
			["/voice"] = true,
		},
		["/targetlastfriend"] = {
			["/targetlastfriend"] = true,
		},
		["/chatlog"] = {
			["/chatlog"] = true,
		},
		["/r"] = {
			["/r"] = true,
			["/reply"] = true,
		},
		["/tts"] = {
			["/tts"] = true,
		},
		["/ma"] = {
			["/ma"] = true,
			["/mainassist"] = true,
		},
		["/ginfo"] = {
			["/guildinfo"] = true,
			["/ginfo"] = true,
		},
		["/stopmacro"] = {
			["/stopmacro"] = true,
		},
		["/v"] = {
			["/v"] = true,
		},
		["/mt"] = {
			["/mt"] = true,
			["/maintank"] = true,
		},
		["/usetoy"] = {
			["/usetoy"] = true,
		},
		["/glist"] = {
			["/whoguild"] = true,
			["/gwho"] = true,
			["/glist"] = true,
		},
		["/bugsack"] = {
			["/bugsack"] = true,
		},
		["/gquit"] = {
			["/gquit"] = true,
			["/guildquit"] = true,
		},
		["/afk"] = {
			["/afk"] = true,
			["/away"] = true,
		},
		["/petautocasttoggle"] = {
			["/petautocasttoggle"] = true,
		},
		["/targetexact"] = {
			["/targetexact"] = true,
		},
		["/random"] = {
			["/rand"] = true,
			["/roll"] = true,
			["/rnd"] = true,
			["/random"] = true,
		},
		["/readycheck"] = {
			["/readycheck"] = true,
		},
		["/overridename"] = {
			["/overridename"] = true,
			["/on"] = true,
		},
		["/wm"] = {
			["/wm"] = true,
			["/worldmarker"] = true,
		},
		["/cleartarget"] = {
			["/cleartarget"] = true,
		},
		["/settitle"] = {
			["/settitle"] = true,
		},
		["/pv"] = {
			["/pv"] = true,
		},
	},
	["Commands"] = {
		["/pvp"] = "/pvp",
		["/party"] = "/p",
		["/countdown"] = "/countdown",
		["/tts"] = "/tts",
		["/petattack"] = "/petattack",
		["/targetparty"] = "/targetparty",
		["/ckick"] = "/ckick",
		["/me"] = "/e",
		["/resetcommentatorsettings"] = "/resetcommentatorsettings",
		["/chatwho"] = "/chatlist",
		["/follow"] = "/f",
		["/a"] = "/a",
		["/petautocaston"] = "/petautocaston",
		["/mute"] = "/mute",
		["/targetlasttarget"] = "/targetlasttarget",
		["/achievements"] = "/ach",
		["/fstack"] = "/framestack",
		["/gdisband"] = "/gdisband",
		["/cast"] = "/cast",
		["/mod"] = "/mod",
		["/groster"] = "/groster",
		["/officer"] = "/o",
		["/ignore"] = "/ignore",
		["/p"] = "/p",
		["/whoguild"] = "/glist",
		["/announce"] = "/announce",
		["/castglyph"] = "/castglyph",
		["/friends"] = "/friends",
		["/charwhisper"] = "/cw",
		["/tell"] = "/w",
		["/macrohelp"] = "/macrohelp",
		["/petfollow"] = "/petfollow",
		["/targetenemyplayer"] = "/targetenemyplayer",
		["/achievement"] = "/ach",
		["/enableaddons"] = "/enableaddons",
		["/on"] = "/overridename",
		["/lfd"] = "/dungeonfinder",
		["/otherraids"] = "/raidbrowser",
		["/target"] = "/target",
		["/nameteam"] = "/nameteam",
		["/pass"] = "/password",
		["/camp"] = "/logout",
		["/tquit"] = "/teamquit",
		["/raidfinder"] = "/raidfinder",
		["/bg"] = "/i",
		["/away"] = "/afk",
		["/guildinfo"] = "/ginfo",
		["/targetlastfriend"] = "/targetlastfriend",
		["/owner"] = "/owner",
		["/g"] = "/g",
		["/targetmarker"] = "/tm",
		["/guildpromote"] = "/gpromote",
		["/remfriend"] = "/removefriend",
		["/clearfocus"] = "/clearfocus",
		["/needbeforegreed"] = "/needbeforegreed",
		["/rsay"] = "/raid",
		["/moderator"] = "/mod",
		["/token"] = "/token",
		["/sh"] = "/y",
		["/cleartarget"] = "/cleartarget",
		["/sp"] = "/summonpet",
		["/dump"] = "/dump",
		["/rw"] = "/rw",
		["/cancelaura"] = "/cancelaura",
		["/f"] = "/f",
		["/castrandom"] = "/castrandom",
		["/worldmarker"] = "/wm",
		["/pv"] = "/pv",
		["/guildmotd"] = "/gmotd",
		["/eventtrace"] = "/eventtrace",
		["/rb"] = "/raidbrowser",
		["/tcaptain"] = "/teamcaptain",
		["/raid"] = "/raid",
		["/group"] = "/group",
		["/m"] = "/macro",
		["/requestinvite"] = "/requestinvite",
		["/targetfriendplayer"] = "/targetfriendplayer",
		["/dismount"] = "/dismount",
		["/share"] = "/share",
		["/lootrolls"] = "/loot",
		["/battleground"] = "/i",
		["/ban"] = "/ban",
		["/reload"] = "/reload",
		["/tinspect"] = "/tinspect",
		["/tdisband"] = "/teamdisband",
		["/guildinvite"] = "/ginvite",
		["/userandom"] = "/userandom",
		["/teamcaptain"] = "/teamcaptain",
		["/targetraid"] = "/targetraid",
		["/community"] = "/community",
		["/instance_chat"] = "/i",
		["/guildremove"] = "/gremove",
		["/ach"] = "/ach",
		["/petautocastoff"] = "/petautocastoff",
		["/chatinfo"] = "/chatlist",
		["/concede"] = "/yield",
		["/master"] = "/master",
		["/s"] = "/s",
		["/help"] = "/h",
		["/yell"] = "/y",
		["/nt"] = "/nameteam",
		["/clearmt"] = "/clearmt",
		["/rf"] = "/raidfinder",
		["/yield"] = "/yield",
		["/etrace"] = "/eventtrace",
		["/console"] = "/console",
		["/exit"] = "/quit",
		["/or"] = "/raidbrowser",
		["/clearma"] = "/clearma",
		["/maoff"] = "/maoff",
		["/macro"] = "/macro",
		["/r"] = "/r",
		["/maintank"] = "/mt",
		["/guilddisband"] = "/gdisband",
		["/mt"] = "/mt",
		["/usetoy"] = "/usetoy",
		["/gquit"] = "/gquit",
		["/forfeit"] = "/yield",
		["/petautocasttoggle"] = "/petautocasttoggle",
		["/random"] = "/random",
		["/overridename"] = "/overridename",
		["/em"] = "/e",
		["/calendar"] = "/calendar",
		["/logout"] = "/logout",
		["/y"] = "/y",
		["/trade"] = "/tr",
		["/stopcasting"] = "/stopcasting",
		["/petmoveto"] = "/petmoveto",
		["/invite"] = "/inv",
		["/quit"] = "/quit",
		["/fol"] = "/f",
		["/tk"] = "/token",
		["/promote"] = "/pr",
		["/cv"] = "/cv",
		["/removefriend"] = "/removefriend",
		["/framestack"] = "/framestack",
		["/tar"] = "/target",
		["/h"] = "/h",
		["/timetest"] = "/timetest",
		["/ginvite"] = "/ginvite",
		["/join"] = "/join",
		["/shout"] = "/y",
		["/stopwatch"] = "/stopwatch",
		["/saveguildroster"] = "/saveguildroster",
		["/cqs"] = "/cancelqueuedspell",
		["/guildhelp"] = "/ghelp",
		["/kick"] = "/u",
		["/chatleave"] = "/leave",
		["/tm"] = "/tm",
		["/timer"] = "/stopwatch",
		["/gdemote"] = "/gdemote",
		["/o"] = "/o",
		["/targetenemy"] = "/targetenemy",
		["/channel"] = "/join",
		["/df"] = "/dungeonfinder",
		["/maintankoff"] = "/mtoff",
		["/ap"] = "/assignplayer",
		["/unban"] = "/unban",
		["/tableinspect"] = "/tinspect",
		["/cancelqueuedspell"] = "/cancelqueuedspell",
		["/assignplayer"] = "/assignplayer",
		["/unmoderator"] = "/unmod",
		["/inspect"] = "/ins",
		["/played"] = "/played",
		["/swapactionbar"] = "/swapactionbar",
		["/busy"] = "/dnd",
		["/clearworldmarker"] = "/cwm",
		["/dismisspet"] = "/dismisspet",
		["/tremove"] = "/teamremove",
		["/gc"] = "/g",
		["/castsequence"] = "/castsequence",
		["/equipset"] = "/equipset",
		["/petdismiss"] = "/petdismiss",
		["/run"] = "/script",
		["/dungeonfinder"] = "/dungeonfinder",
		["/greplace"] = "/greplace",
		["/squelch"] = "/mute",
		["/ginfo"] = "/ginfo",
		["/guilddemote"] = "/gdemote",
		["/clearmaintank"] = "/clearmt",
		["/petdefensive"] = "/petdefensive",
		["/teamquit"] = "/teamquit",
		["/chatlog"] = "/chatlog",
		["/cancelform"] = "/cancelform",
		["/guild"] = "/g",
		["/lfr"] = "/raidfinder",
		["/gremove"] = "/gremove",
		["/click"] = "/click",
		["/buggrabber"] = "/buggrabber",
		["/startattack"] = "/startattack",
		["/use"] = "/use",
		["/osay"] = "/o",
		["/changeactionbar"] = "/changeactionbar",
		["/u"] = "/u",
		["/chatlist"] = "/chatlist",
		["/settitle"] = "/settitle",
		["/targetfriend"] = "/targetfriend",
		["/tinvite"] = "/teaminvite",
		["/loot"] = "/loot",
		["/leavevehicle"] = "/leavevehicle",
		["/ffa"] = "/ffa",
		["/focus"] = "/focus",
		["/rand"] = "/random",
		["/mainassist"] = "/ma",
		["/c"] = "/c",
		["/disableaddons"] = "/disableaddons",
		["/invitespectatormatch"] = "/invitespectatormatch",
		["/mainassistoff"] = "/maoff",
		["/e"] = "/e",
		["/assist"] = "/a",
		["/raidinfo"] = "/raidinfo",
		["/resetchat"] = "/resetchat",
		["/emote"] = "/e",
		["/who"] = "/who",
		["/bugsack"] = "/bugsack",
		["/ann"] = "/announce",
		["/petaggressive"] = "/petaggressive",
		["/say"] = "/s",
		["/pr"] = "/pr",
		["/equipslot"] = "/equipslot",
		["/guildroster"] = "/groster",
		["/instance"] = "/i",
		["/script"] = "/script",
		["/ra"] = "/raid",
		["/t"] = "/w",
		["/gf"] = "/guildfinder",
		["/uninvite"] = "/u",
		["/equip"] = "/equip",
		["/teamremove"] = "/teamremove",
		["/combatlog"] = "/combatlog",
		["/unsquelch"] = "/unmute",
		["/unmod"] = "/unmod",
		["/rnd"] = "/random",
		["/friend"] = "/friends",
		["/gpromote"] = "/gpromote",
		["/chan"] = "/join",
		["/summonpet"] = "/summonpet",
		["/clear"] = "/clear",
		["/chat"] = "/chat",
		["/petstay"] = "/petstay",
		["/stopattack"] = "/stopattack",
		["/unignore"] = "/unignore",
		["/password"] = "/password",
		["/cinvite"] = "/cinvite",
		["/randomfavoritepet"] = "/randomfavoritepet",
		["/ma"] = "/ma",
		["/randompet"] = "/randompet",
		["/stopspelltarget"] = "/stopspelltarget",
		["/targetlastenemy"] = "/targetlastenemy",
		["/petpassive"] = "/petpassive",
		["/v"] = "/v",
		["/reply"] = "/r",
		["/wg"] = "/wargame",
		["/votekick"] = "/u",
		["/chathelp"] = "/chat",
		["/unvoice"] = "/mute",
		["/w"] = "/w",
		["/whisper"] = "/w",
		["/tr"] = "/tr",
		["/send"] = "/w",
		["/targetexact"] = "/targetexact",
		["/roll"] = "/random",
		["/rfp"] = "/randomfavoritepet",
		["/clearmainassist"] = "/clearma",
		["/gwho"] = "/glist",
		["/inv"] = "/inv",
		["/achieve"] = "/ach",
		["/moderate"] = "/moderate",
		["/usetalents"] = "/usetalents",
		["/guildleader"] = "/gleader",
		["/roundrobin"] = "/roundrobin",
		["/api"] = "/api",
		["/vt"] = "/vt",
		["/gu"] = "/g",
		["/gleader"] = "/gleader",
		["/chatinvite"] = "/cinvite",
		["/time"] = "/time",
		["/petassist"] = "/petassist",
		["/csay"] = "/c",
		["/cwm"] = "/cwm",
		["/eq"] = "/equip",
		["/dnd"] = "/dnd",
		["/mtoff"] = "/mtoff",
		["/leave"] = "/leave",
		["/chatexit"] = "/leave",
		["/unmute"] = "/unmute",
		["/voice"] = "/unmute",
		["/ghelp"] = "/ghelp",
		["/teamdisband"] = "/teamdisband",
		["/readycheck"] = "/readycheck",
		["/threshold"] = "/threshold",
		["/?"] = "/h",
		["/raidbrowser"] = "/raidbrowser",
		["/stopmacro"] = "/stopmacro",
		["/sw"] = "/stopwatch",
		["/guildquit"] = "/gquit",
		["/gmotd"] = "/gmotd",
		["/glist"] = "/glist",
		["/i"] = "/i",
		["/un"] = "/u",
		["/cw"] = "/cw",
		["/wargame"] = "/wargame",
		["/guildfinder"] = "/guildfinder",
		["/duel"] = "/duel",
		["/afk"] = "/afk",
		["/teaminvite"] = "/teaminvite",
		["/wm"] = "/wm",
		["/gv"] = "/gv",
		["/ins"] = "/ins",
		["/spell"] = "/cast",
	},
}
